GitlabCIMultiRunner:
  image: recteurlp/gitlab-ci-multi-runner-fedora
  volumes:
    - /opt/gitlab-ci-multi-runner-fedora:/home/gitlab_ci_multi_runner/data
  environment:
    - CI_SERVER_URL=
    - RUNNER_TOKEN=
    - RUNNER_DESCRIPTION=
    - RUNNER_EXECUTOR=shell
  restart: always
