GitlabCIMultiRunner:
  image: recteurlp/gitlab-runner-fedora
  volumes:
    - /opt/gitlab-runner-fedora:/home/gitlab_runner/data
  environment:
    - CI_SERVER_URL=
    - RUNNER_TOKEN=
    - RUNNER_DESCRIPTION=
    - RUNNER_EXECUTOR=shell
  restart: always
